#pragma once
#include <string>
#include <vector>
#include <memory>
#include <iostream>
#include <array>
#include <unordered_map>
#include <fstream>
#include <sstream>
#include "Debug/Profiler.h"
#include <functional>
#include <filesystem>
#include <thread>
#include <chrono>
#include <mono/jit/jit.h>
#include <mono/metadata/assembly.h>
#include <mono/metadata/object.h>
#include <mono/metadata/debug-helpers.h>
